using Pkg
Pkg.update()
Pkg.add("Mux")
Pkg.add("Interact")
Pkg.add("Distributions")
Pkg.add("CmdStan")
Pkg.add("StatsPlots")
Pkg.add(PackageSpec(name="StatsModels",version="0.5"))
Pkg.add("RCall")
#Pkg.add("Gadfly")
